/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/
public class Problem_2 // Even Fibonacci numbers
{
    public static void main(String[] args)
    {
    	int sum = 2;
    	int i = 2;

    	int array[] = new int[50];
		array[0] = 1;
		array[1] = 2;

		while(true)
		{
			array[i] = array[i-1] + array[i-2];
			if(array[i]>4000000)break;
			if(array[i]%2==0)
			{
				sum+=array[i];
			}
			i++;
		}
		System.out.println(sum);

    }
}
